# Generated by Django 4.2 on 2025-04-05 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, verbose_name='Project Title')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (January - March)'), (2, 'Q2 (April - June)'), (3, 'Q3 (July - September)'), (4, 'Q4 (October - December)')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('status', models.CharField(choices=[('SUBM', 'Submitted'), ('APPR', 'Approved'), ('REJ', 'Rejected')], default='SUBM', max_length=5)),
                ('sector', models.CharField(choices=[('HEL', 'Health'), ('EDU', 'Education'), ('GEN', 'Gender'), ('ENV', 'Environment'), ('AGR', 'Agriculture'), ('WAT', 'Water and satitation'), ('ECO', 'Economic empowerment'), ('SOC', 'Social Protection'), ('GOV', 'Governane'), ('INF', 'Infrastructure'), ('OTH', 'Other')], max_length=5)),
                ('district', models.CharField(default='Ilemela', editable=False, max_length=20, verbose_name='District')),
                ('ward', models.CharField(choices=[('NYAKATO', 'Nyakato'), ('BUSWELU', 'Buswelu'), ('ILEMELA', 'Ilemela'), ('PASIANSI', 'Pasiansi'), ('BUGOBWA', 'Bugogwa'), ('SANGABUYE', 'Sangabuye'), ('MECCO', 'MECCO'), ('BUZURUGA', 'Buzuruga'), ('NYASAKA', 'Nyasaka'), ('KAHAMA', 'Kahama'), ('KISEKE', 'Kiseke'), ('KAYENZE', 'Kayenze'), ('SHIBULA', 'Shibula'), ('KAWEEKAMO', 'Kawekamo'), ('KITANGIRI', 'Kitangiri'), ('KIRUMBA', 'Kirumba'), ('NYAMANORO', 'Nyamanoro'), ('IBUNGILO', 'Ibungilo'), ('NYAMHONGOLO', 'Nyamhongolo')], max_length=20, verbose_name='Ward')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('summary', models.TextField(verbose_name='Executive Summary')),
                ('activities', models.TextField(verbose_name='Activities Conducted')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount Used (TZS)')),
                ('indicators', models.CharField(choices=[('PER', 'Performance Indicators'), ('MUN', 'Municipality Indicators'), ('NAT', 'National Indicators'), ('SDG', 'SDG Indicators')], max_length=5)),
                ('per_indicators', models.CharField(max_length=200)),
                ('target', models.IntegerField(default=0, verbose_name='Target')),
                ('achieved', models.IntegerField(default=0, verbose_name='Achieved')),
                ('outcomes', models.TextField(verbose_name='Outcomes and Impact')),
                ('challenges', models.TextField(verbose_name='Challenges and Solutions')),
                ('men', models.IntegerField(default=0, verbose_name='Men Beneficiaries')),
                ('women', models.IntegerField(default=0, verbose_name='Women Beneficiaries')),
                ('youth', models.IntegerField(default=0, verbose_name='Youth Beneficiaries')),
                ('sdg_alignment', models.CharField(choices=[('1', 'No Poverty'), ('2', 'Zero Hunger'), ('3', 'Good Health and Well-being'), ('4', 'Quality Education'), ('5', 'Gender Equality'), ('6', 'Clean Water and Sanitation'), ('7', 'Affordable and Clean Energy'), ('8', 'Decent Work and Economic Growth'), ('9', 'Industry, Innovation and Infrastructure'), ('10', 'Reduced Inequalities'), ('11', 'Sustainable Cities and Communities'), ('12', 'Responsible Consumption and Production'), ('13', 'Climate Action'), ('14', 'Life Below Water'), ('15', 'Life on Land'), ('16', 'Peace, Justice and Strong Institutions'), ('17', 'Partnerships for the Goals')], max_length=2, verbose_name='Sustainable Development Goal')),
                ('indicator', models.CharField(choices=[('CLIMATE_CHANGE_RESILIENCE', 'Climate Change Resilience'), ('ACCESS_TO_LAND_AND_CREDIT', 'Access to land and credit'), ('CROP_YIELD_AGRICULTURAL_PRODUCTIVITY', 'Crop Yield & Agricultural Productivity'), ('FOOD_SECURITY_MALNUTRITION_RATES', 'Food Security & Malnutrition Rates'), ('REPRESENTATION_WOMEN_LEADERSHIP', 'Representation of women in leadership'), ('GENDER_BASED_VIOLENCE_REDUCED', 'Gender-Based Violence Reduced')], max_length=50, verbose_name='SDG Indicator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approved/Rejected by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report')),
            ],
        ),
    ]
