# Generated by Django 4.2 on 2025-04-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-year', '-quarter'], 'permissions': [('can_review_report', 'Can review and approve/reject reports')]},
        ),
        migrations.AddField(
            model_name='report',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Review Notes'),
        ),
        migrations.AddField(
            model_name='report',
            name='status_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
